name: Build and publish API documentation

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'corretto'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Build with Gradle
                run: ./gradlew build dokkaGenerate

            -   name: Deploy to GitHub Pages
                if: success()
                uses: crazy-max/ghaction-github-pages@v4
                with:
                    target_branch: gh-pages
                    build_dir: build/docs
                    keep_history: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-ios:
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'corretto'

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Build with Gradle
                run: ./gradlew build
