name: Release IOS build artifacts to Maven Central

on:
    workflow_dispatch:

jobs:
    publish-ios:
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'corretto'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Publish artifacts
                run: ./gradlew check publishToSonatype closeAndReleaseSonatypeStagingRepository
                env:
                    SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
                    SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
